apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: celery
  name: celery
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: celery
    spec:
      containers:
      - args:
        - /bin/sh
        - /data/recruitment/worker.start.sh
        image: registry.cn-beijing.aliyuncs.com/ihopeit/django-recruitment:0.9
        name: recruit-celery
        resources: {}
        volumeMounts:
        - mountPath: /data/recruitment
          name: celery-claim0
      restartPolicy: Always
      volumes:
      - name: celery-claim0
        persistentVolumeClaim:
          claimName: celery-claim0
status: {}
