apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: celery-claim0
spec:
  storageClassName: alicloud-disk-available
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
