apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: flower
  name: flower
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: flower
    spec:
      containers:
      - args:
        - /bin/sh
        - /data/recruitment/flower.start.sh
        image: registry.cn-beijing.aliyuncs.com/ihopeit/django-recruitment:0.9
        name: recruit-flower
        ports:
        - containerPort: 5555
        resources: {}
        volumeMounts:
        - mountPath: /data/recruitment
          name: flower-claim0
      restartPolicy: Always
      volumes:
      - name: flower-claim0
        persistentVolumeClaim:
          claimName: flower-claim0
status: {}
