apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: django-recruitment
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
        app: django-recruitment
    spec:
      containers:
      - args:
        - /bin/sh
        - /data/recruitment/start.local.bat
        env:
        - name: server_params
          value: --settings=settings.local
        ######### environment variables for logtail to SLS ###########
        - name: aliyun_logs_recruitment-web
          value: stdout
        - name: aliyun_logs_recruitment-web
          value: /var/log/*.log
        - name: aliyun_logs_mytag1_tags
          value: tag1=v1
        image: registry.cn-beijing.aliyuncs.com/ihopeit/django-recruitment:0.9
        name: recruitment-web
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /data/logs/recruitment
          name: web-claim0
      restartPolicy: Always
      volumes:
      - name: web-claim0
        persistentVolumeClaim:
          claimName: web-claim0
status: {}
